parameters:
  displayName: 'Copy files batch to Blob Storage'
  sourcePath: ''
  sourcePattern: '*.*'
  azureSubscription: ''
  storageAccount: ''
  containerName: ''
  destinationPath: ''
  overwrite: false
steps:
- task: AzureCLI@2
  displayName: ${{ parameters.displayName }}
  inputs:
    azureSubscription: '${{parameters.azureSubscription}}'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch -s ${{ parameters.sourcePath }} --pattern ${{ parameters.sourcePattern }} -d ${{ parameters.containerName }} --destination-path drop/${{ parameters.destinationPath }} --account-name ${{ parameters.storageAccount }} --overwrite ${{ parameters.overwrite }} --auth-mode login'