parameters:
  sourceBaseFolder: ''
  destinationBaseFolder: ''
  modules: []

steps:
- ${{ each module in parameters.modules }} :
  - template: create_package_task.yml
    parameters:
      packageFolder: ${{ parameters.sourceBaseFolder }}/${{module.module}}
      packageName: ${{module.module}}
      packageVersion: ${{module.version}}
      destinationFolder: '${{ parameters.destinationBaseFolder }}'
