parameters:
- name: environmentObjects
  type: object
  default:
  - environmentName: 'dev'
    dependsOn: ''
    regionAbrvs: ['cus']
    azureServiceConnectionName: Azure-WGOOwnerAppNonProd-SmartRV
    azureStorageAccount: stdldevicetypesjxuuhqwbk
    deviceTypesFunctionUrlBase: https://func-wgo-winnconnect-device-types-cus-dev.azurewebsites.net/api
    devicesFunctionUrlBase: https://func-wgo-winnconnect-devices-cus-dev.azurewebsites.net/api
    functionApiKeyName: PIPELINE_FUNCTION_KEY_DEV
  - environmentName: 'tst'
    dependsOn: 'dev'
    regionAbrvs: ['cus']
    azureServiceConnectionName: Azure-WGOOwnerAppTest-SmartRV
    azureStorageAccount: stdldevicetypesj3pyszyf7
    deviceTypesFunctionUrlBase: https://func-wgo-winnconnect-device-types-cus-tst.azurewebsites.net/api
    devicesFunctionUrlBase: https://func-wgo-winnconnect-devices-cus-tst.azurewebsites.net/api
    functionApiKeyName: PIPELINE_FUNCTION_KEY_TEST
  - environmentName: 'prd'
    dependsOn: 'tst'
    regionAbrvs: ['cus']
    azureServiceConnectionName: Azure-WGOOwnerAppProd-SmartRV
    azureStorageAccount: stdldevicetypesk2rcm6gdk
    deviceTypesFunctionUrlBase: https://func-wgo-winnconnect-device-types-cus-prd.azurewebsites.net/api
    devicesFunctionUrlBase: https://func-wgo-winnconnect-devices-cus-prd.azurewebsites.net/api
    functionApiKeyName: PIPELINE_FUNCTION_KEY_PROD
##
##  functionApiKeyName parameter value must be a hidden variable which contains value
##  that is a function api key for following functions:
##  devices/query (GET), devices/registrations/reset (POST)
##  devices/registrations (POST), and releases (POST)
##
- name: serviceName
  type: string
  default: 'wgo_smart_rv_onboard'
- name: deviceType
  type: string
  default: 'common'
- name: isRelease
  displayName: is this an official release?
  type: boolean
  default: false
- name: publish
  displayName: publish to test cohorts
  type: boolean
  default: false
- name: cohorts
  displayName: cohorts
  type: string
- name: smartRvVersion
  type: string
  default: '1.0.0'
- name: modules
  type: object
  default: []

stages:
- template: ./stages/build_stage.yml
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}
    serviceName: ${{ parameters.serviceName }}
    deviceType: ${{ parameters.deviceType }}
    smartRvVersion: ${{ parameters.smartRvVersion}}
    modules: ${{ parameters.modules}}
- ${{ each environmentObject in parameters.environmentObjects }} :
  - template: ./stages/deploy_stage.yml
    parameters:
      environmentName: ${{ environmentObject.environmentName }}
      serviceName: ${{ parameters.serviceName }}
      regionAbrvs: ${{environmentObject.regionAbrvs}}
      dependsOnEnv: ${{ environmentObject.dependsOn }}
      azureServiceConnectionName: ${{ environmentObject.azureServiceConnectionName }}
      azureStorageAccount: ${{ environmentObject.azureStorageAccount }}
      deviceType: ${{ parameters.deviceType }}
      smartRvVersion: ${{ parameters.smartRvVersion }}
      cohorts: ${{ parameters.cohorts}}
      isRelease: ${{ convertToJson(parameters.isRelease) }}
      publish: ${{ convertToJson(parameters.publish) }}
      modules: ${{ parameters.modules}}
      deviceTypesFunctionUrlBase: ${{ environmentObject.deviceTypesFunctionUrlBase }}
      devicesFunctionUrlBase: ${{ environmentObject.devicesFunctionUrlBase }}
      functionApiKeyName: ${{ environmentObject.functionApiKeyName }}