trigger: none

parameters:
- name: deviceType
  displayName: device type
  type: string
  values:
  - s500
  - s800
  - sbox
  default: s500
- name: isRelease
  displayName: is this an official release?
  type: boolean
  default: false
- name: publish
  displayName: publish to test cohorts
  type: boolean
  default: false
- name: cohorts
  displayName: test cohorts for publish
  type: string
  default: alpha

variables:
  - template: variables/smartrv_version_variables.yml
  - name: isRelease
    value: false
  - name: appendCounter
    value: $[counter(format('{0}', variables['smartRvVersion']), 1)]
  - name: version
    value: $[format('{0}-validation-{1}', variables['smartRvVersion'],  variables['appendCounter'])]

name: '$(version)'

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: templates
    type: git
    name: 'Owners App/templates'
    ref: 'refs/heads/main'
  - repository: frontend
    type: git
    name: 'SmartRV/Frontend'
    ref: 'refs/heads/main'

stages:
- template: wgo-smart-rv-validate-build-template.yml
  parameters:
    deviceType: ${{ parameters.deviceType }}
    isRelease: ${{ parameters.isRelease }}
    publish: ${{ parameters.publish }}
    cohorts: ${{ parameters.cohorts }}
    smartRvVersion: $(Build.BuildNumber)
    modules:
    - module: data
      version: ${{ variables.dataModuleVersion }}
      container: common
    - module: hmi_tools
      version: ${{ variables.hmiToolsModuleVersion }}
      container: common
    - module: iot_service
      version: ${{ variables.iotServiceModuleVersion }}
      container: common
    - module: system_service
      version: ${{ variables.systemServiceModuleVersion }}
      container: common
    - module: main_service
      version: ${{ variables.uiServiceModuleVersion }}
      container: common
    - module: kiosk_config
      version: ${{ variables.kioskConfigModuleVersion }}
      container: common
    - module: can_service
      version: ${{ variables.canServiceModuleVersion }}
      container: common
    - module: bt_service
      version: ${{ variables.btServiceModuleVersion }}
      container: common
    - module: update_service
      version: ${{ variables.updateServiceModuleVersion }}
      container: common
    - module: common_libs
      version: ${{ variables.commonLibsModuleVersion }}
      container: common
    - module: smartrv-frontend
      version: ${{ variables.smartrvFrontendModuleVersion }}
      container: common
