parameters:
- name: environmentObjects
  type: object
  default:
  - environmentName: 'dev'
    dependsOn: ''
    regionAbrvs: ['cus']
    azureServiceConnectionName: 'Azure-WGOOwnerAppNonProd-SmartRV'
    azureStorageAccount: 'stdldevicetypesjxuuhqwbk'
    deviceTypesFunctionUrlBase: ''
    devicesFunctionUrlBase: ''
    functionApiKeyName: ''
    cohorts: ''

- name: serviceName
  type: string
  default: 'wgo_smart_rv_onboard'
- name: deviceType
  type: string
  default: 'common'
- name: isRelease
  displayName: is this an official release?
  type: boolean
  default: false
- name: publish
  displayName: publish to test cohorts
  type: boolean
  default: false
- name: smartRvVersion
  type: string
  default: '1.0.0'
- name: cohorts
  type: string
- name: modules
  type: object
  default: []

stages:
- template: ./stages/build_stage.yml
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}
    serviceName: ${{ parameters.serviceName }}
    deviceType: ${{ parameters.deviceType }}
    isRelease: ${{ parameters.isRelease }}
    publish: ${{ parameters.publish }}
    smartRvVersion: ${{ parameters.smartRvVersion}}
    cohorts: ${{ parameters.cohorts}}
    modules: ${{ parameters.modules}}
